### ISSUE TITLE
升级到php8.2报错

### ISSUE THREAD

**Issue by waughf** [ken678/framework#1]
Fatal error: Uncaught Error: Interface "Psr\Container\ContainerInterface" not found in D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Container.php:53 Stack trace: #0 D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Loader.php(411): include() #1 D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Loader.php(132): think\__include_file() #2 D:\phpstudy_pro\WWW\2024\thinkphp\library\think\exception\Handle.php(42): think\Loader::autoload() #3 D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Error.php(51): think\exception\Handle->report() #4 [internal function]: think\Error::appException() #5 {main} thrown in D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Container.php on line 53

Fatal error: Uncaught Error: Interface "Psr\Container\ContainerInterface" not found in D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Container.php:53 Stack trace: #0 D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Loader.php(411): include() #1 D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Loader.php(132): think\__include_file() #2 D:\phpstudy_pro\WWW\2024\thinkphp\library\think\exception\Handle.php(42): think\Loader::autoload() #3 D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Error.php(51): think\exception\Handle->report() #4 D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Error.php(90): think\Error::appException() #5 [internal function]: think\Error::appShutdown() #6 {main} thrown in D:\phpstudy_pro\WWW\2024\thinkphp\library\think\Container.php on line 53

**Comment by ken678** [comment]
目前新版已经使用tp8.0
